[package]
name = "actix-web"
version = "0.7.0-dev"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix web is a simple, pragmatic and extremely fast web framework for Rust."
readme = "README.md"
keywords = ["http", "web", "framework", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-web/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-server",
              "web-programming::http-client",
              "web-programming::websocket"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]
build = "build.rs"

[badges]
travis-ci = { repository = "actix/actix-web", branch = "master" }
appveyor = { repository = "fafhrd91/actix-web-hdy9d" }
codecov = { repository = "actix/actix-web", branch = "master", service = "github" }

[lib]
name = "actix_web"
path = "src/lib.rs"

[features]
default = ["session", "brotli", "flate2-c"]

# tls
tls = ["native-tls", "tokio-tls"]

# openssl
alpn = ["openssl", "tokio-openssl"]

# sessions feature, session require "ring" crate and c compiler
session = ["cookie/secure"]

# brotli encoding, requires c compiler
brotli = ["brotli2"]

# miniz-sys backend for flate2 crate
flate2-c = ["flate2/miniz-sys"]

# rust backend for flate2 crate
flate2-rust = ["flate2/rust_backend"]

[package.metadata.docs.rs]
features = ["tls", "alpn", "session", "brotli", "flate2-c"]

[dependencies]
#actix = "^0.6.0"
actix = { git = "https://github.com/redox-os/actix" }

base64 = "0.9"
bitflags = "1.0"
failure = "0.1.1"
h2 = { git = "https://github.com/redox-os/h2" }
http = "^0.1.5"
httparse = "1.2"
http-range = "0.1"
libc = { git = "https://github.com/redox-os/liblibc" }
log = "0.4"
mime = "0.3"
mime_guess = "2.0.0-alpha"
num_cpus = "1.0"
percent-encoding = "1.0"
rand = "0.5"
regex = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"
sha1 = "0.6"
smallvec = "0.6"
time = "0.1"
encoding = "0.2"
language-tags = "0.2"
lazy_static = "1.0"
url = { version="1.7", features=["query_encoding"] }
cookie = { version="0.10", features=["percent-encode"] }
brotli2 = { version="^0.3.2", optional = true }
flate2 = { version="1.0", optional = true, default-features = false }

# io
mio = { git = "https://github.com/redox-os/mio" }
net2 = { git = "https://github.com/redox-os/net2-rs" }
bytes = "0.4"
byteorder = "1"
futures = "0.1"
futures-cpupool = "0.1"
slab = "0.4"
tokio = { git = "https://github.com/redox-os/tokio" }
tokio-io = { git = "https://github.com/redox-os/tokio" }
tokio-tcp = { git = "https://github.com/redox-os/tokio" }
tokio-timer = { git = "https://github.com/redox-os/tokio" }
tokio-reactor = { git = "https://github.com/redox-os/tokio" }

# native-tls
native-tls = { version="0.1", optional = true }
tokio-tls = { git = "https://github.com/redox-os/tokio-tls", optional = true }

# openssl
openssl = { version="0.10", optional = true }
tokio-openssl = { version="0.2", optional = true }

[dev-dependencies]
env_logger = "0.5"
serde_derive = "1.0"

[build-dependencies]
version_check = "0.1"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[workspace]
members = [
  "./",
  "tools/wsload/",
]
